### PR TITLE
Warning when not using 2.4GHz network

### LINKED ISSUE #19: Need a warning that only 2.4G networks will work
In the example SmartConfig app it autodetects networks that are not 2.4G and generates a warning message. If this is not possible, at least we need somewhere that tells people to make sure they are using the 2.4Ghz wifi network if available.

image

### LINKED ISSUE #27: Layout change screen 5
Alignment: Left-align header text and text below
Font: Slightly increase font size
Font: Format “OpenEEW Dashboard” text as a link
Font: Font color = slightly more gray, #575757 
Move button between “Next steps” and “Login to the OpenEEW dashboard…”

Screen 5

### PR DESCRIPTION
**Pull request by NavarroFer**
I found this package [wifi_info_plugin](https://pub.dev/packages/wifi_info_plugin) that allows to get the frequency of the connected network.
Closes #19 

Changes where made in the page **complete.dart**
Closes #27

### CODE REVIEW

**Comment by NavarroFer** [comment]
Hello! I'm a student from [Universidad Nacional de Mar del Plata](https://www.fi.mdp.edu.ar/), My friend and I have been working on a college project and we've found your project on linuxfoundation.org and would like to make a collaboration to fix the issues #19 and #27. Please let us know what you think. Thank you!

By the way, the [contributing page](https://openeew.com/docs/contributing) link you provided is not working! :)

**Comment by NavarroFer** [comment]
Hello! I'm a student from [Universidad Nacional de Mar del Plata](https://www.fi.mdp.edu.ar/), My friend and I have been working on a college project and we've found your project on linuxfoundation.org and would like to make a collaboration to fix the issues #19 and #27. Please let us know what you think. Thank you!

By the way, the [contributing page](https://openeew.com/docs/contributing) link you provided is not working! :)

**Comment by johnwalicki** [comment]
This is great! I looked over the patch. I want to compile and test it on 2.4Ghz and 5Ghz and mixed networks

**Review by johnwalicki — CHANGES_REQUESTED** [review]
Line 29  
```
final colorGrey
```
should use the Carbon palette.  #878787 is between gray40 and gray50. We use gray40 in forms/provision.dart.

Suggest using `CColors.gray40` instead of a hard coded colorGrey.
No need for a variable, just reference CColors.gray40 in the two places the patch references it. 

```
    'gray': (
      10: #f4f4f4,
      20: #e0e0e0,
      30: #c6c6c6,
      40: #a8a8a8,
      50: #8d8d8d,
      60: #6f6f6f,
      70: #525252,
      80: #393939,
      90: #262626,
      100: #161616,
    ),
```

**Comment by NavarroFer** [comment]
I'll do this changes!

**Comment by johnwalicki** [comment]
Thanks - I compiled and tested on various 2.4GHz / 5GHz / mixed networks.  Took some screenshots.

You might want to join the OpenEEW Slack workspace.  I posted the screenshots of the new changes in the #apps channel.
See link on the upper right corner of https://openeew.com/

**Comment by NahuelM97** [comment]
Hi! Nahuel here, Fer's project workmate. First of all, thank you for your review! We've made the change you suggested.

A small thing we thought we should mention: the values used in `MIN_WIFI_FREQUENCY` and `MAX_WIFI_FREQUENCY` are the standarized values specified in [IEEE 802.11b](https://en.wikipedia.org/wiki/IEEE_802.11b-1999). If you think the range should be a little bit more flexible, let us know and we'll change it! :)

**Review by johnwalicki — APPROVED** [review]
Looks good to me.

**Comment by johnwalicki** [comment]
Fantastic - merging the PR.

**Comment by andygrillo** [comment]
Hola @NavarroFer y @NahuelM97 !

Mil gracias por tu trabajo. Ya tenemos la nueva  version del app en el play store gracias a ustedes!

**Comment by johnwalicki** [comment]
@NavarroFer y @NahuelM97 - This improvement is now available in the Google Playstore.  Thanks!
We would welcome you in the OpenEEW Slack workspace.  We have some more Flutter features we want to implement.

**Pull request merged**
